config/routes.rb
Rails.application.routes.draw do

devise_for :admins

root 'homes#top'

post '/' => 'homes#create'

resources :newss

get '/areacontents' => 'homes#area'

get '/meo' => 'homes#meo'

get '/site' => 'homes#site'

get '/sns' => 'homes#sns'

get '/listing' => 'homes#listing'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    new_newss_path
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @newss = News.page(params[:page]).per(3).reverse_order
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.save
    flash[:success] = "お問い合わせありがとうございます。入力頂いたメールアドレス宛にお返事させて頂きますので今しばらくお待ちください。"
    ContactMailer.contact_mail(@contact).deliver
    redirect_to root_path
  end

  private
    def  contact_params
    params.permit(:name, :address, :body)
  end

end

app/controllers/newss_controller.rb
class NewssController < ApplicationController

before_action :authenticate_admin!

  def new
    @news = News.new
    @newss = News.page(params[:page]).per(3).reverse_order
  end

  def create
    news = News.new(news_params)
    news.save
    redirect_to new_newss_path
  end

  def destroy
    news = News.find(params[:id])
    news.destroy
    redirect_to new_newss_path
  end

  private
    def  news_params
    params.require(:news).permit(:body, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/newss_helper.rb
module NewssHelper
end

app/views/homes/area.html.erb
<%= render 'template/header' %>

<div class="bodys">

<h1>エリアコンテンツKW分析 詳細ページ</h1>

</div>

<%= render 'template/footer' %>

app/views/homes/listing.html.erb
<%= render 'template/header' %>

<div class="bodys">

<h1>リスティング広告運用 詳細ページ</h1>

</div>

<%= render 'template/footer' %>

app/views/homes/meo.html.erb
<%= render 'template/header' %>

<div class="bodys">

<h1>MEO 詳細ページ</h1>

</div>

<%= render 'template/footer' %>

app/views/homes/site.html.erb
<%= render 'template/header' %>

<div class="bodys">

<h1>自社予約サイト制作 詳細ページ</h1>

</div>

<%= render 'template/footer' %>

app/views/homes/sns.html.erb
<%= render 'template/header' %>

<div class="bodys">

<h1>SNS企画・運用 詳細ページ</h1>

</div>

<%= render 'template/footer' %>

app/views/homes/top.html.erb
<!-- ヘッダー　----------------------------------------------------------->

<div class="pc">
  <%= render 'template/top_header' %>
</div>

<div class="sp">
  <%= render 'template/sp_header' %>
</div>

<!-- 問い合わせありがとうメッセージ　----------------------------------------------------------->

<% if flash[:success] %>
  <div class="thanks">
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  </div>
<% end %>

<!-- pc用トップ　----------------------------------------------------------->

<div class="pc">

<div class="video">
  <%= video_tag("Luxe.mp4", autoplay: :true, muted: :true, loop: :true, class: 'video-content') %>
</div>

<div class="concept">
  <p class="title">「見方が変われば世界は変わる」</p>
  <p class="mission">Our Mission</p>
  <p class="text">日本国内のあらゆる宿泊施設のバリューを最大化すると共に、<br>宿泊されるユーザー様に安心・安全で楽しんで頂ける施設創りを我々は追求いたします。</p>
</div>

</div>


<!-- sp用トップ　----------------------------------------------------------->

<div class="sp">

<div class="box">
  <div class="images">
    <div class="image1"></div>
    <div class="image2"></div>
    <div class="image3"></div>
  </div>
</div>

<div class="sp-top">
  <p class="title">「見方が変われば世界は変わる」</p><br><br>
  <p class="mission">Our Mission</p>
  <p class="text">日本国内のあらゆる宿泊施設のバリューを最大化すると共に、<br>宿泊されるユーザー様に安心・安全で<br>楽しんで頂ける施設創りを我々は追求いたします。</p>
</div>

</div>


<!-- ニュース　----------------------------------------------------------->

<div class="news"><br><br>
  <p class="title">News</p><br><br>

  <div class="container">

    <% @newss.each do |news| %>

    <div class="col-sm-4">
      <div class="content">
        <div class="day"><hr class="sp">
          <%= news.created_at.strftime('%Y/%m/%d')%><div class="sp"><br></div>
        </div><hr class="pc">
        <div>
          <%= simple_format(news.body) %>
        </div>
        <div class="rinku">
        <%= raw Rinku.auto_link(simple_format(news.url))%>
        </div>
      </div>
    </div>
    <% end %>

  </div>

  <div class="center"><br><br>
    <%= paginate @newss %>
  </div>

</div>


<!-- 社訓　----------------------------------------------------------->

<div class="motto"><div class="pc"><br><br><br></div>
  <div class="col-sm-3">
  </div>
  <div class="col-sm-6"><div class="sp"><br></div>
    <p class="motto-title">Vision</p><br><br>
    <div class="motto-text">
      <p class="pc">
        2020年時点に日本全国の宿泊施設数は5.2万施設あり、<br><br>
        部屋数にすると162.5万室と言われています。<br><br>
        近年はコロナ禍において運営難の宿泊施設が数多く存在します。<br><br>
        この中でも特にインバウンド需要に頼り切った施設づくりを<br><br>
        行っている事で、
      </p>
      <p class="sp">
        2020年時点に日本全国の宿泊施設数は<br>
        5.2万施設あり、部屋数にすると<br>
        162.5万室と言われています。<br><br>
        近年はコロナ禍において運営難の<br>
        宿泊施設が数多く存在します。<br><br>
        この中でも特にインバウンド需要に<br>
        頼り切った施設づくりを行っている事で、
      </p>
    </div>
  </div>
</div>


<!-- サービス　----------------------------------------------------------->

<div class="service", id="Service">
  <p class="title">Service</p>

  <div class="list area">
    <div class="mask">
      <%= link_to areacontents_path do %>
      <div class="text">
        <div class="head">エリアコンテンツ<div class="sp"></div>KW分析</div><hr>
        <div class="explain">
          テキストテキストテキストテキスト<br>
          テキストテキストテキストテキスト<br>
          テキストテキストテキストテキスト<br>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="list meo">
    <div class="mask">
      <%= link_to meo_path do %>
      <div class="text">
        <div class="head">MEO<span style="font-size:2rem;">(Map Engine Optimization)</span></div><hr>
        <div class="explain">
          テキストテキストテキストテキスト<br>
          テキストテキストテキストテキスト<br>
          テキストテキストテキストテキスト<br>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="list site">
    <div class="mask">
      <%= link_to site_path do %>
      <div class="text">
        <div class="head">自社予約サイト制作</div><hr>
        <div class="explain">
          テキストテキストテキストテキスト<br>
          テキストテキストテキストテキスト<br>
          テキストテキストテキストテキスト<br>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="list sns">
    <div class="mask">
      <%= link_to sns_path do %>
      <div class="text">
        <div class="head">SNS企画・運用</div><hr>
        <div class="explain">
          テキストテキストテキストテキスト<br>
          テキストテキストテキストテキスト<br>
          テキストテキストテキストテキスト<br>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="list listing">
    <div class="mask">
      <%= link_to listing_path do %>
      <div class="text">
        <div class="head">リスティング広告<div class="sp"></div>運用</div><hr>
        <div class="explain">
          テキストテキストテキストテキスト<br>
          テキストテキストテキストテキスト<br>
          テキストテキストテキストテキスト<br>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>


<!-- 会社概要　----------------------------------------------------------->


<div class="company center", id="Company">
  <div class="title">Company</div>

  <div class="container">
    <div class="col-sm-6">
      <table class="table">
        <tr>
          <th class="col-xs-3"><p></p>社名</th>
          <td class="col-xs-9"><p></p>株式会社Luxe Resorts<p></p></td>
        </tr>
        <tr>
          <th><p></p>代表取締役</th>
          <td><p></p>末吉 力朗<p></p></td>
        </tr>
        <tr>
          <th><p></p>所在地</th>
          <td><p></p>大阪府大阪市北区天満2-8-17 天満橋パークビル4階<p></p></td>
        </tr>
        <tr>
          <th><p></p>電話番号</th>
          <td><p></p>06-7182-2493</td>
        </tr>
      </table>
    </div>
    <div class="col-sm-6">
      <table class="table">
        <tr>
          <th class="col-xs-3"><p></p>設立</th>
          <td class="col-xs-9"><p></p>0000年0月0日<p></p></td>
        </tr>
        <tr>
          <th><p></p>資本金</th>
          <td><p></p>000,000円<p></p></td>
        </tr>
        <tr>
          <th><p></p>従業員数</th>
          <td><p></p>00名<p></p></td>
        </tr>
        <tr>
          <th><p></p>事業内容</th>
          <td><p></p>テキストテキストテキストテキスト</td>
        </tr>
      </table>
    </div>
  </div>

</div>


<!-- 問い合わせ　----------------------------------------------------------->

<div class="contact center", id="Contact">

  <div class="title">Contact</div>

  <div class="form">

    <P class="text">
      ご依頼・お問い合わせは下記フォーマットにてご送信下さい。<br><br>
      お電話での対応も承ってますのでお気軽にお問い合わせ下さい。<br><br>
      電話番号：06-7182-2493(平日10:00-18:00)
    </P>

  <div class="container"><br><br>

    <div class="col-sm-3">
    </div>

    <div class="col-sm-6">

    <%= form_with model:@contact, url: root_path do |f| %>

      <div>
  	    <%= f.text_field :name, placeholder: "ご担当者様", class:'form-control' %>
      </div><br><br><br>
      <div>
  	    <%= f.text_field :address, placeholder: "連絡先メールアドレス、または電話番号", class:'form-control' %>
      </div><br><br><br><br>
      <div>
  	    <%= f.text_area :body, placeholder: "お問い合わせ内容", class:'form-control', rows: 7%>
      </div><br><br><br><br>

      <div><%= f.submit '送信', class:"btn", data: { confirm: "この内容で送信してよろしいですか？" }%></div>

    <% end %>

    </div>

  </div>

  </div>


</div>


<!-- フッター　----------------------------------------------------------->

<div class="pc">
  <%= render 'template/top_footer' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luxe Resorts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/newss/new.html.erb
<%= link_to destroy_admin_session_path, method: :delete do %>
  <p class="adminheader">Luxe Resorts</p>
<% end %>

<div class="center"><br><br>

  <h3>新規投稿</h3><br>

    <div class="container">
    <div class="row">
    <div class="col-sm-4 col-sm-offset-4">

    <%= form_with model:@news, url: newss_index_path do |f| %>

      <h4><%= Date.current.strftime('%Y/%m/%d')%></h4>

      <div>
  	    <%= f.text_area :body, placeholder: "投稿内容(改行も反映されます)", class:'form-control', rows: 5, autofocus: true %>
      </div><br>

      <div>
        <%= f.text_field :url, placeholder: "URL(無くても投稿できます)", class:'form-control', rows: 5 %>
      </div><br>

      <div><%= f.submit '新規投稿',class:"btn btn-success"%></div><br>

    <% end %>

    </div>
    </div>
    <hr>
    </div>


  <h3>一覧確認・削除</h3><br><br><br><br><br><br>

    <div class="news">

    <div class="container">

      <% @newss.each do |news| %>

        <div class="col-sm-4">
          <div class="content">
            <div class="day">
              <%= news.created_at.strftime('%Y/%m/%d')%>
            </div><hr>
            <div>
              <%= simple_format(news.body) %>
            </div>
            <div class="rinku">
              <%= raw Rinku.auto_link(simple_format(news.url))%>
            </div>
            <div><%= link_to '削除', newss_path(news),class: 'btn btn-danger', method: :delete, data: { confirm: "この記事を削除してよろしいですか？" } %></div>
          </div>
        </div>

      <% end %>

    </div>

    </div>

    <div><br><br>
      <%= paginate @newss %>
    </div>

</div>

app/views/template/_footer.html.erb
<footer>
  	<div class="row">

      <div class="col-sm-2">
      	<%= link_to root_path(anchor: 'Service') do %>
          <br><br><p class="list"><i class="fas fa-users"></i> SERVICE</p>
        <% end %>
      </div>

      <div class="col-sm-2">
        <%= link_to root_path(anchor: 'Company') do %>
          <br><br><p class="list"><i class="far fa-building"></i> COMPANY</p>
        <% end %>
      </div>

      <div class="col-sm-2">
        <%= link_to root_path(anchor: 'Contact') do %>
          <br><br><p class="list"><i class="far fa-envelope"></i> CONTACT</p>
        <% end %>
      </div>

      <div class="col-sm-6">
        <%= link_to root_path do %>
          <p class="title">Luxe Resorts</p>
        <% end %>
      </div>

    </div>

      <p class="address">大阪府大阪市北区天満2-8-17<br>天満橋パークビル4階<br>06-7182-2493</p>

</footer>

app/views/template/_header.html.erb
<header>

    <div class="col-sm-6">
      <%= link_to root_path do %>
      <p class="title">Luxe Resorts</p>
      <% end %>
    </div>


    <div class="col-sm-2">
      <li class="dropdown">
        <a class="dropdown-toggle list" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="far fa-building"></i> SERVICE <i class="fas fa-bars"></i></a>
        <ul class="dropdown-menu">
          <li><a href="/areacontents">1.</i> エリアコンテンツ分析</a></li>
          <li><a href="/meo">2.</i> MEO</a></li>
          <li><a href="/site">3.</i> 自社予約サイト制作</a></li>
          <li><a href="/sns">4.</i> SNS企画・運用</a></li>
          <li><a href="/listing">5.</i> リスティング広告運用</a></li>
        </ul>
      </li>
    </div>

    <div class="col-sm-2">
      <%= link_to root_path(anchor: 'Company') do %>
        <p class="list"><i class="far fa-building"></i> COMPANY</p>
      <% end %>
    </div>

    <div class="col-sm-2">
      <%= link_to root_path(anchor: 'Contact') do %>
        <p class="list"><i class="far fa-envelope"></i> CONTACT</p>
      <% end %>
    </div>

</header>

app/views/template/_sp_header.html.erb
<div class="sp-header container">
<div class="row">


<div class="col-xs-9">

  <%= link_to root_path do %>
  <div class="logo">Luxe Resorts</div><!-- /.logo -->
  <% end %>

</div>

<div class="col-xs-3">

  <!-- ハンバーガーメニュー部分 -->
  <div class="drawer">
    <!-- ハンバーガーメニューの表示・非表示を切り替えるチェックボックス -->
    <input type="checkbox" id="drawer-check" class="drawer-hidden" >

    <!-- ハンバーガーアイコン -->
    <label for="drawer-check" class="drawer-open"><span></span></label>

    <!-- 追加：メニューを閉じるための要素 -->
    <label for="drawer-check" class="drawer-close"></label>

    <!-- メニュー -->
    <nav class="drawer-content">
      <ul class="drawer-list">
        <li class="drawer-item">
          <br><p class="menu"> Service</p><br>
        <i class="far fa-chart-bar"></i><%= link_to " エリアコンテンツ分析", areacontents_path %>
        </li><hr class="border"><!-- /.drawer-item -->
        <li class="drawer-item">
          <i class="fas fa-map-marker-alt"></i><%= link_to " MEO", meo_path %>
        </li><hr class="border"><!-- /.drawer-item -->
        <li class="drawer-item">
          <i class="fas fa-desktop"></i><%= link_to " 自社予約サイト制作", site_path %>
        </li><hr class="border"><!-- /.drawer-item -->
        <li class="drawer-item">
          <i class="fab fa-twitter"></i><%= link_to " SNS企画・運用", sns_path %>
        </li><hr class="border">
        <li class="drawer-item">
          <i class="far fa-address-card"></i><%= link_to " リスティング広告運用", listing_path %>
        </li><hr class="border">
      </ul><!-- /.drawer-list -->
    </nav>

  </div>

</div>

</div>
</div>

app/views/template/_top_footer.html.erb
<footer>
  	<div class="row">

      <div class="col-sm-2">
      	<%= link_to '#Service' do %>
          <br><br><p class="list"><i class="fas fa-users"></i> SERVICE</p>
        <% end %>
      </div>

      <div class="col-sm-2">
        <%= link_to '#Company' do %>
          <br><br><p class="list"><i class="far fa-building"></i> COMPANY</p>
        <% end %>
      </div>

      <div class="col-sm-2">
        <%= link_to '#Contact' do %>
          <br><br><p class="list"><i class="far fa-envelope"></i> CONTACT</p>
        <% end %>
      </div>

      <div class="col-sm-6">
        <span id="back">
          <a href="#">
            <p class="title">Luxe Resorts</p>
          </a>
        </span>
      </div>

    </div>

      <p class="address">大阪府大阪市北区天満2-8-17<br>天満橋パークビル4階<br>06-7182-2493</p>

</footer>

app/views/template/_top_header.html.erb
<header>

    <div class="col-sm-6">
      <%= link_to root_path do %>
      <p class="title">Luxe Resorts</p>
      <% end %>
    </div>


    <div class="col-sm-2">
      <li class="dropdown">
        <a class="dropdown-toggle list" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="far fa-building"></i> SERVICE <i class="fas fa-bars"></i></a>
        <ul class="dropdown-menu">
          <li><a href="/areacontents">1.</i> エリアコンテンツ分析</a></li>
          <li><a href="/meo">2.</i> MEO</a></li>
          <li><a href="/site">3.</i> 自社予約サイト制作</a></li>
          <li><a href="/sns">4.</i> SNS企画・運用</a></li>
          <li><a href="/listing">5.</i> リスティング広告運用</a></li>
        </ul>
      </li>
    </div>

    <div class="col-sm-2">
      <%= link_to '#Company' do %>
        <p class="list"><i class="far fa-building"></i> COMPANY</p>
      <% end %>
    </div>

    <div class="col-sm-2">
      <%= link_to '#Contact' do %>
        <p class="list"><i class="far fa-envelope"></i> CONTACT</p>
      <% end %>
    </div>

</header>